import { RawSchemeInput } from './validator';

export const MAHARASHTRA_OFFICIAL_RAW_SCHEMES: RawSchemeInput[] = [
  // =========================================================================
  // 1. WOMEN & CHILD DEVELOPMENT DEPARTMENT (MAHARASHTRA)
  // =========================================================================
  {
    title: 'Mukhyamantri Majhi Ladki Bahin Yojana',
    description: 'Flagship economic empowerment scheme by the Government of Maharashtra providing direct monthly financial assistance of ₹1,500 to women aged 21 to 65 years with annual family income up to ₹2.5 Lakh.',
    department: 'Women and Child Development Department',
    category: 'Women & Child Welfare',
    state: 'Maharashtra',
    minAge: 21,
    maxAge: 65,
    maxIncome: 250000,
    targetGender: 'Female',
    targetOccupation: 'All Citizens',
    socialCategory: 'All',
    applyLink: 'https://ladakibahin.maharashtra.gov.in',
    sourceUrl: 'https://ladakibahin.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Lek Ladki Yojana',
    description: 'Financial empowerment and girl-child support scheme providing cumulative ₹1,01,000 cash assistance at different educational stages from birth up to 18 years for girls born in yellow or orange ration card families.',
    department: 'Women and Child Development Department',
    category: 'Women & Child Welfare',
    state: 'Maharashtra',
    minAge: 0,
    maxAge: 18,
    maxIncome: 250000,
    targetGender: 'Female',
    targetOccupation: 'Student',
    socialCategory: 'All',
    applyLink: 'https://womenchild.maharashtra.gov.in',
    sourceUrl: 'https://womenchild.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Mukhyamantri Annapurna Yojana',
    description: 'Free cooking fuel initiative providing 3 free domestic LPG gas cylinder refills per year to women beneficiaries of Ladki Bahin Yojana and Pradhan Mantri Ujjwala Yojana across Maharashtra.',
    department: 'Food, Civil Supplies and Consumer Protection',
    category: 'Women & Child Welfare',
    state: 'Maharashtra',
    minAge: 21,
    maxAge: 65,
    maxIncome: 250000,
    targetGender: 'Female',
    targetOccupation: 'All Citizens',
    socialCategory: 'All',
    applyLink: 'https://mahafood.gov.in',
    sourceUrl: 'https://mahafood.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Navtejaswini Maharashtra Rural Women’s Enterprise Program',
    description: 'Comprehensive rural women empowerment and self-help group (SHG) enterprise incubation initiative providing micro-finance, skill training, and market access support through MAVIM.',
    department: 'Women and Child Development Department',
    category: 'Women & Child Welfare',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: 60,
    maxIncome: 250000,
    targetGender: 'Female',
    targetOccupation: 'Entrepreneur',
    socialCategory: 'All',
    applyLink: 'https://mavimindia.org',
    sourceUrl: 'https://mavimindia.org',
    sourceType: 'MahaDBT'
  },

  // =========================================================================
  // 2. AGRICULTURE & FARMER WELFARE (MAHADBT KRISHI & MP-SIMS)
  // =========================================================================
  {
    title: 'Namo Shetkari Maha Samman Nidhi Yojana',
    description: 'Maharashtra state government farmer income support providing ₹6,000 annually in 3 installments of ₹2,000, paid directly via DBT on top of the Central PM-KISAN scheme for a total of ₹12,000/year.',
    department: 'Department of Agriculture',
    category: 'Agriculture & Krishi (MahaDBT / MP-SIMS)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Farmer',
    socialCategory: 'All',
    applyLink: 'https://mahadbt.maharashtra.gov.in/Farmer',
    sourceUrl: 'https://mpsims.maharashtra.gov.in/MPSIMSWEB/schemePublicList',
    sourceType: 'MP-SIMS'
  },
  {
    title: 'Mukhyamantri Baliraja Vij Savlat Yojana',
    description: '100% electricity bill waiver for agricultural water pumps up to 7.5 Horsepower (HP) capacity for all farmers in Maharashtra for 5 consecutive years, providing free irrigation power.',
    department: 'Energy Department & MSEDCL',
    category: 'Agriculture & Krishi (MahaDBT / MP-SIMS)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Farmer',
    socialCategory: 'All',
    applyLink: 'https://www.mahadiscom.in',
    sourceUrl: 'https://mpsims.maharashtra.gov.in',
    sourceType: 'MP-SIMS'
  },
  {
    title: 'Mukhyamantri Shashwat Krishi Sinchan Yojana',
    description: 'Special drip and sprinkler micro-irrigation capital subsidy scheme offering 80% to 85% government subsidy to small and marginal farmers across drought-prone and suicide-affected districts of Maharashtra.',
    department: 'Department of Agriculture',
    category: 'Agriculture & Krishi (MahaDBT / MP-SIMS)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Farmer',
    socialCategory: 'All',
    applyLink: 'https://mahadbt.maharashtra.gov.in/Farmer',
    sourceUrl: 'https://mpsims.maharashtra.gov.in/MPSIMSWEB/schemePublicList',
    sourceType: 'MP-SIMS'
  },
  {
    title: 'Magel Tyala Saur Krishi Pump Yojana (PM-KUSUM Component-B)',
    description: 'Off-grid solar agricultural water pump installation scheme providing 90% to 95% subsidy for 3 HP, 5 HP, and 7.5 HP solar DC pumps to provide daytime farm irrigation for farmers without conventional electric connection.',
    department: 'Energy Department & MEDA',
    category: 'Agriculture & Krishi (MahaDBT / MP-SIMS)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Farmer',
    socialCategory: 'All',
    applyLink: 'https://www.mahadiscom.in/solar_MTSKPY/',
    sourceUrl: 'https://mpsims.maharashtra.gov.in',
    sourceType: 'MP-SIMS'
  },
  {
    title: 'Magel Tyala Shet-tale (Farm Ponds on Demand Scheme)',
    description: 'Individual farm water harvesting pond scheme providing direct DBT cash subsidy of up to ₹50,000 for digging plastic-lined farm ponds to ensure protective irrigation during dry spells.',
    department: 'Department of Agriculture',
    category: 'Agriculture & Krishi (MahaDBT / MP-SIMS)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Farmer',
    socialCategory: 'All',
    applyLink: 'https://mahadbt.maharashtra.gov.in/Farmer',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'State Agricultural Mechanization Scheme (Krishi Yantrikikaran)',
    description: 'MahaDBT farmer mechanization scheme providing 40% to 50% subsidy on procurement of tractors, power tillers, rotavators, seed drills, multi-crop threshers, and harvesting equipment.',
    department: 'Department of Agriculture',
    category: 'Agriculture & Krishi (MahaDBT / MP-SIMS)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Farmer',
    socialCategory: 'All',
    applyLink: 'https://mahadbt.maharashtra.gov.in/Farmer',
    sourceUrl: 'https://mpsims.maharashtra.gov.in/MPSIMSWEB/schemePublicList',
    sourceType: 'MP-SIMS'
  },
  {
    title: 'Dr. Babasaheb Ambedkar Krushi Swavalamban Yojana',
    description: 'Special agricultural development scheme for Scheduled Caste (SC) and Nav-Bouddha farmers providing up to ₹2.5 Lakh financial assistance for new borewells, open wells, in-well boring, pumpsets, and drip irrigation.',
    department: 'Department of Agriculture & Social Justice',
    category: 'Agriculture & Krishi (MahaDBT / MP-SIMS)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: 150000,
    targetGender: 'Any',
    targetOccupation: 'Farmer',
    socialCategory: 'SC/ST',
    applyLink: 'https://mahadbt.maharashtra.gov.in/Farmer',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Birsa Munda Krishi Kranti Yojana',
    description: '100% state subsidized farm infrastructure scheme for Scheduled Tribe (ST) farmers in Maharashtra providing funding for new open irrigation wells, solar pumps, farm ponds, and electricity connection.',
    department: 'Tribal Development Department & Agriculture',
    category: 'Agriculture & Krishi (MahaDBT / MP-SIMS)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: 150000,
    targetGender: 'Any',
    targetOccupation: 'Farmer',
    socialCategory: 'SC/ST',
    applyLink: 'https://mahadbt.maharashtra.gov.in/Farmer',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Gopinath Munde Shetkari Apghat Suraksha Sanugrah Anudan Yojana',
    description: 'Universal accidental welfare and insurance aid providing ₹2,00,000 ex-gratia compensation to the legal heir in case of accidental death or permanent total disability of an active farmer in Maharashtra.',
    department: 'Department of Agriculture',
    category: 'Agriculture & Krishi (MahaDBT / MP-SIMS)',
    state: 'Maharashtra',
    minAge: 10,
    maxAge: 75,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Farmer',
    socialCategory: 'All',
    applyLink: 'https://krishi.maharashtra.gov.in',
    sourceUrl: 'https://krishi.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },

  // =========================================================================
  // 3. HIGHER & TECHNICAL EDUCATION (DHE, DTE, DMER SCHOLARSHIPS ON MAHADBT)
  // =========================================================================
  {
    title: 'Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna (EBC)',
    description: 'Flagship higher education fee concession scheme on MahaDBT offering 50% tuition and exam fee reimbursement for Economically Backward Class (EBC) open and general category students with annual family income up to ₹8 Lakh.',
    department: 'Directorate of Higher Education (DHE) & DTE',
    category: 'MahaDBT (Higher Education)',
    state: 'Maharashtra',
    minAge: 17,
    maxAge: 32,
    maxIncome: 800000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'EWS',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Dr. Panjabrao Deshmukh Vastigruh Nirvah Bhatta Yojna',
    description: 'Hostel maintenance allowance scheme providing ₹30,000/year (in municipal corporation areas) and ₹20,000/year (other areas) to children of registered marginal landholding farmers and EBC students in professional courses.',
    department: 'Directorate of Higher Education (DHE) & DTE',
    category: 'MahaDBT (Higher Education)',
    state: 'Maharashtra',
    minAge: 17,
    maxAge: 32,
    maxIncome: 800000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'All',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Rajarshi Chhatrapati Shahu Maharaj Technical Education Fee Reimbursement',
    description: '50% tuition fee and examination fee waiver for students admitted through Centralized Admission Process (CAP) in Engineering, Architecture, Pharmacy, MCA, MBA, and Polytechnic courses.',
    department: 'Directorate of Technical Education (DTE)',
    category: 'MahaDBT (Technical Education)',
    state: 'Maharashtra',
    minAge: 16,
    maxAge: 32,
    maxIncome: 800000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'All',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Rajarshi Chhatrapati Shahu Maharaj Medical Fee Reimbursement (DMER)',
    description: '50% fee concession for Economically Backward Class (EBC) and open category students admitted to MBBS, BDS, BAMS, BHMS, BPTH, and Nursing courses in government and private unaided medical colleges.',
    department: 'Directorate of Medical Education and Research (DMER)',
    category: 'MahaDBT (Medical Education)',
    state: 'Maharashtra',
    minAge: 17,
    maxAge: 30,
    maxIncome: 800000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'All',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'State Government Open Merit Scholarship',
    description: 'Merit-based financial award for top-scoring undergraduate Arts, Commerce, and Science degree students in Maharashtra universities who secured 60%+ in 12th standard.',
    department: 'Directorate of Higher Education (DHE)',
    category: 'MahaDBT (Higher Education)',
    state: 'Maharashtra',
    minAge: 17,
    maxAge: 25,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'All',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },

  // =========================================================================
  // 4. SOCIAL JUSTICE & SPECIAL ASSISTANCE (SJSA MAHADBT)
  // =========================================================================
  {
    title: 'Government of India Post-Matric Scholarship for SC Students (MahaDBT)',
    description: '100% complete tuition fee waiver, examination fee refund, and monthly maintenance allowance paid via DBT for Scheduled Caste and Nav-Bouddha students in 11th, 12th, Diploma, Degree, and PG courses.',
    department: 'Social Justice and Special Assistance Department',
    category: 'MahaDBT (Social Justice)',
    state: 'Maharashtra',
    minAge: 16,
    maxAge: 35,
    maxIncome: 250000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'SC/ST',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Post-Matric Tuition Fee and Examination Fee (SC Freeship)',
    description: 'Full tuition and examination fee reimbursement for Scheduled Caste students whose family annual income exceeds ₹2.5 Lakh with no upper income cap for fee concession.',
    department: 'Social Justice and Special Assistance Department',
    category: 'MahaDBT (Social Justice)',
    state: 'Maharashtra',
    minAge: 16,
    maxAge: 35,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'SC/ST',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Dr. Babasaheb Ambedkar Swadhar Yojana',
    description: 'Direct hostel, mess, and educational allowance of ₹51,000 to ₹60,000 per year transferred into the bank account of eligible SC students studying in professional and higher education colleges who do not get government hostel seats.',
    department: 'Social Justice and Special Assistance Department',
    category: 'MahaDBT (Social Justice)',
    state: 'Maharashtra',
    minAge: 17,
    maxAge: 30,
    maxIncome: 250000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'SC/ST',
    applyLink: 'https://sjsa.maharashtra.gov.in',
    sourceUrl: 'https://sjsa.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Sanjay Gandhi Niradhar Anudan Yojana',
    description: 'Monthly social security pension of ₹1,500 for destitute elderly persons, widows, divorced women, deserted wives, orphans, and persons with severe disabilities who have family income below ₹21,000/year.',
    department: 'Social Justice and Special Assistance Department',
    category: 'MahaDBT (Social Justice)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: 65,
    maxIncome: 21000,
    targetGender: 'Any',
    targetOccupation: 'Senior Citizen',
    socialCategory: 'All',
    applyLink: 'https://sjsa.maharashtra.gov.in',
    sourceUrl: 'https://sjsa.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Shravanbal Seva Rajya Nivruttivetan Yojana',
    description: 'State old-age pension scheme granting ₹1,500/month direct financial assistance to destitute senior citizens aged 65 years and above residing in Maharashtra with annual income under ₹21,000.',
    department: 'Social Justice and Special Assistance Department',
    category: 'MahaDBT (Social Justice)',
    state: 'Maharashtra',
    minAge: 65,
    maxAge: null,
    maxIncome: 21000,
    targetGender: 'Any',
    targetOccupation: 'Senior Citizen',
    socialCategory: 'All',
    applyLink: 'https://sjsa.maharashtra.gov.in',
    sourceUrl: 'https://sjsa.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },

  // =========================================================================
  // 5. TRIBAL DEVELOPMENT DEPARTMENT (TDD MAHADBT)
  // =========================================================================
  {
    title: 'Government of India Post-Matric Scholarship for ST Students (MahaDBT)',
    description: '100% tuition, exam fee waiver and monthly maintenance support for Scheduled Tribe (ST) students in higher secondary, graduation, post-graduation, and medical/engineering colleges.',
    department: 'Tribal Development Department',
    category: 'MahaDBT (Tribal Development)',
    state: 'Maharashtra',
    minAge: 16,
    maxAge: 35,
    maxIncome: 250000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'SC/ST',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Pandit Deendayal Upadhyay Swayam Yojana',
    description: 'Direct annual financial allowance of ₹51,000 (divisional level), ₹43,000 (district level), and ₹38,000 (taluka level) disbursed directly into the bank accounts of ST tribal college students who could not get admission into government hostels.',
    department: 'Tribal Development Department',
    category: 'MahaDBT (Tribal Development)',
    state: 'Maharashtra',
    minAge: 17,
    maxAge: 30,
    maxIncome: 250000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'SC/ST',
    applyLink: 'https://tribal.maharashtra.gov.in',
    sourceUrl: 'https://tribal.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Shabari Awas Gharkul Yojana',
    description: '100% rural and semi-urban permanent housing financial subsidy of up to ₹1,30,000 to ₹2,50,000 for homeless and kutcha-house dwelling Scheduled Tribe families across Maharashtra.',
    department: 'Tribal Development Department & Rural Housing',
    category: 'Housing & Gharkul',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: 100000,
    targetGender: 'Any',
    targetOccupation: 'All Citizens',
    socialCategory: 'SC/ST',
    applyLink: 'https://tribal.maharashtra.gov.in',
    sourceUrl: 'https://tribal.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },

  // =========================================================================
  // 6. VJNT, OBC AND SBC WELFARE DEPARTMENT (MAHADBT)
  // =========================================================================
  {
    title: 'Post-Matric Scholarship for VJNT, OBC and SBC Students',
    description: 'Tuition and exam fee reimbursement along with maintenance allowances for Vimukta Jatis, Nomadic Tribes, Other Backward Classes, and Special Backward Category students with family income up to ₹1.5 Lakh.',
    department: 'VJNT, OBC and SBC Welfare Department',
    category: 'MahaDBT (OBC & VJNT Welfare)',
    state: 'Maharashtra',
    minAge: 16,
    maxAge: 35,
    maxIncome: 150000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'OBC',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Tuition Fees and Examination Fees for VJNT/OBC/SBC (Freeship)',
    description: 'Fee reimbursement scheme for VJNT, OBC, and SBC students having family annual income between ₹1.5 Lakh and ₹8.0 Lakh enrolled in recognized undergraduate and postgraduate degree/diploma courses.',
    department: 'VJNT, OBC and SBC Welfare Department',
    category: 'MahaDBT (OBC & VJNT Welfare)',
    state: 'Maharashtra',
    minAge: 16,
    maxAge: 35,
    maxIncome: 800000,
    targetGender: 'Any',
    targetOccupation: 'Student',
    socialCategory: 'OBC',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Gyanjyoti Savitribai Phule Aadhaar Yojana',
    description: 'Hostel and meal direct cash allowance of up to ₹60,000 per year for OBC, VJNT, and SBC category girl students pursuing higher professional education away from their hometowns in Maharashtra.',
    department: 'VJNT, OBC and SBC Welfare Department',
    category: 'MahaDBT (OBC & VJNT Welfare)',
    state: 'Maharashtra',
    minAge: 17,
    maxAge: 30,
    maxIncome: 250000,
    targetGender: 'Female',
    targetOccupation: 'Student',
    socialCategory: 'OBC',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Modi Awas Gharkul Yojana',
    description: 'Dedicated housing construction financial assistance scheme granting ₹1,20,000 subsidy to eligible Other Backward Class (OBC) beneficiaries in rural Maharashtra to construct permanent pucca homes.',
    department: 'VJNT, OBC and SBC Welfare Department',
    category: 'Housing & Gharkul',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: null,
    maxIncome: 120000,
    targetGender: 'Any',
    targetOccupation: 'All Citizens',
    socialCategory: 'OBC',
    applyLink: 'https://mahadbt.maharashtra.gov.in',
    sourceUrl: 'https://mahadbt.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },

  // =========================================================================
  // 7. SKILL DEVELOPMENT & EMPLOYMENT (MAHASWAYAM)
  // =========================================================================
  {
    title: 'Mukhyamantri Yuva Karya Prashikshan Yojana (CM Youth Internship)',
    description: 'Massive youth skill internship program in Maharashtra offering 6 months on-the-job industrial apprenticeship with monthly government stipends of ₹6,000 (12th Pass), ₹8,000 (ITI/Diploma), and ₹10,000 (Graduates/PG).',
    department: 'Skill Development, Employment and Entrepreneurship',
    category: 'Skill Development & Employment (MahaSwayam)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: 35,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Unemployed',
    socialCategory: 'All',
    applyLink: 'https://rojgar.mahaswayam.gov.in',
    sourceUrl: 'https://mahaswayam.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Maharashtra Apprenticeship Promotion Scheme (MAPS)',
    description: 'State government apprenticeship reimbursement scheme providing ₹1,500 per month wage subsidy to employers for hiring local youth as certified apprentices across micro, small, and medium enterprises.',
    department: 'Skill Development, Employment and Entrepreneurship',
    category: 'Skill Development & Employment (MahaSwayam)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: 35,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Unemployed',
    socialCategory: 'All',
    applyLink: 'https://www.apprenticeshipindia.gov.in',
    sourceUrl: 'https://mahaswayam.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Annasaheb Patil Arthik Vikas Mahamandal Project Loan Scheme',
    description: 'Interest-free self-employment project loan subsidy scheme offering 100% interest reimbursement on bank business loans up to ₹10 Lakh to ₹15 Lakh for Maratha and open category entrepreneurs.',
    department: 'Skill Development & Annasaheb Patil Mahamandal',
    category: 'Skill Development & Employment (MahaSwayam)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: 50,
    maxIncome: 800000,
    targetGender: 'Any',
    targetOccupation: 'Entrepreneur',
    socialCategory: 'General',
    applyLink: 'https://mahasharaddh.in',
    sourceUrl: 'https://mahasharaddh.in',
    sourceType: 'MahaDBT'
  },

  // =========================================================================
  // 8. PUBLIC HEALTH & CASHLESS HOSPITALIZATION
  // =========================================================================
  {
    title: 'Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY Universal)',
    description: 'Universal state health insurance scheme providing up to ₹5,00,000 cashless hospital treatment per family per year covering 1,356 medical/surgical procedures across 1,000+ empanelled government and private network hospitals.',
    department: 'Public Health Department & State Health Assurance Society',
    category: 'Health & Medical Welfare',
    state: 'Maharashtra',
    minAge: null,
    maxAge: null,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'All Citizens',
    socialCategory: 'All',
    applyLink: 'https://www.jeevandayee.gov.in',
    sourceUrl: 'https://www.jeevandayee.gov.in',
    sourceType: 'MahaDBT'
  },

  // =========================================================================
  // 9. LABOUR WELFARE (BOCW CONSTRUCTION WORKERS)
  // =========================================================================
  {
    title: 'Maharashtra BOCW Bandhkam Kamgar Welfare Schemes',
    description: 'Comprehensive welfare umbrella for registered construction workers providing free essential safety kits, ₹5,000 to ₹1,00,000 children education scholarships, ₹75,000 marriage grant, and ₹5 hot cooked meals under Atal Aahar.',
    department: 'Labour Department (Maharashtra BOCW Board)',
    category: 'Labour & BOCW Welfare',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: 60,
    maxIncome: null,
    targetGender: 'Any',
    targetOccupation: 'Worker',
    socialCategory: 'All',
    applyLink: 'https://mahabocw.in',
    sourceUrl: 'https://mahabocw.in',
    sourceType: 'MahaDBT'
  },

  // =========================================================================
  // 10. SENIOR CITIZENS & DIVYANG WELFARE
  // =========================================================================
  {
    title: 'Chief Minister Vayoshree Yojana',
    description: 'State assistance scheme providing ₹3,000 one-time financial grant directly via DBT into bank accounts of senior citizens aged 65 years and above to purchase physical assistive devices (wheelchairs, spectacles, hearing aids).',
    department: 'Social Justice and Special Assistance Department',
    category: 'MahaDBT (Social Justice)',
    state: 'Maharashtra',
    minAge: 65,
    maxAge: null,
    maxIncome: 200000,
    targetGender: 'Any',
    targetOccupation: 'Senior Citizen',
    socialCategory: 'All',
    applyLink: 'https://sjsa.maharashtra.gov.in',
    sourceUrl: 'https://sjsa.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  },
  {
    title: 'Divyang Motorized Tricycle & Assistive Aid Scheme',
    description: '100% subsidized motorized tricycles, smart canes, laptops with screen readers, and self-employment business toolkits for persons with 40% and above benchmark disabilities in Maharashtra.',
    department: 'Divyang Welfare Department',
    category: 'MahaDBT (Social Justice)',
    state: 'Maharashtra',
    minAge: 18,
    maxAge: 55,
    maxIncome: 300000,
    targetGender: 'Any',
    targetOccupation: 'Persons with Disabilities',
    socialCategory: 'All',
    applyLink: 'https://sjsa.maharashtra.gov.in',
    sourceUrl: 'https://sjsa.maharashtra.gov.in',
    sourceType: 'MahaDBT'
  }
];
